
export const RECEIVE_DOCUMENTS = 'RECEIVE_DOCUMENTS';
export const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS';
export const INITIALIZE_DOCUMENTS = 'INITIALIZE_DOCUMENTS';
export const CHANGE_TABLE_NAME = 'CHANGE_TABLE_NAME';