
export const RECEIVE_DOCUMENTS = 'RECEIVE_DOCUMENTS';
export const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS';
export const REFRESH_DOCUMENTS_TABLE = 'REFRESH_DOCUMENTS_TABLE';
export const CHANGE_DOCUMENTS_TABLE = 'CHANGE_DOCUMENTS_TABLE';
export const UPDATE_DOCUMENTS_LIST = 'UPDATE_DOCUMENTS_LIST';
